services:
  - type: web
    name: telegram-prediction-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        value: 7870128724:AAF0zniFAw9RSuqFSofv5GEPk-5GEtRlRhw
      - key: BOT_USERNAME
        value: Aviator_confirm_bot
      - key: CHANNEL_USERNAME
        value: testsub01
    healthCheckPath: /